# Generated by Django 4.0.1 on 2022-01-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GBEX_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='antigenbodybatch',
            name='Location',
        ),
        migrations.RemoveField(
            model_name='celllinebatch',
            name='Location',
        ),
        migrations.RemoveField(
            model_name='culturemediabatch',
            name='Location',
        ),
        migrations.RemoveField(
            model_name='grna',
            name='Location',
        ),
        migrations.RemoveField(
            model_name='plasmidbatch',
            name='Location',
        ),
        migrations.RemoveField(
            model_name='primers',
            name='Location',
        ),
        migrations.RemoveField(
            model_name='strainbatch',
            name='Location',
        ),
        migrations.AlterField(
            model_name='antigenbody',
            name='BindsTo',
            field=models.ManyToManyField(blank=True, to='GBEX_app.AntiGenBody'),
        ),
    ]
