# Generated by Django 3.2.9 on 2021-11-15 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('rows', models.PositiveIntegerField()),
                ('columns', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('pos_index', models.PositiveIntegerField()),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='GBEX_storage.box')),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('parent_loc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='GBEX_storage.location')),
            ],
        ),
        migrations.AddField(
            model_name='box',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='GBEX_storage.location'),
        ),
    ]
