# Generated by Django 3.2.9 on 2021-11-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GBEX_storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vial',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
