# Generated by Django 4.0.1 on 2022-01-18 13:51

import GBEX_app.models.Inventory
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('GBEX_storage', '0004_remove_vial_pos_index_vial_box_column_vial_box_row_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vial',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vial',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('model', GBEX_app.models.Inventory.AntiGenBodyBatch), ('model', GBEX_app.models.Inventory.CellLineBatch), ('model', GBEX_app.models.Inventory.CultureMediaBatch), ('model', GBEX_app.models.Inventory.PlasmidBatch), ('model', GBEX_app.models.Inventory.StrainBatch), ('model', GBEX_app.models.Inventory.gRNA), ('model', GBEX_app.models.Inventory.Primers), ('model', GBEX_app.models.Inventory.Toxins), _connector='OR'), null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='vial',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
